version: "3.7"

services:
  neo4j:
    image: humanconnection/neo4j:latest
    build:
      context: neo4j
    networks:
      - hc-neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7687:7687
      - 7474:7474
  backend:
    networks:
      - hc-network
      - hc-neo4j
    ports:
      - 4000:4000
      - 4001:4001
    image: humanconnection/nitro-backend:latest
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - GRAPHQL_PORT=4000
      - GRAPHQL_URI=http://localhost:4000
      - CLIENT_URI=http://localhost:3000
      - JWT_SECRET=b/&&7b78BF&fv/Vd
      - MOCK=false
      - MAPBOX_TOKEN=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
    depends_on:
      - neo4j
